; PlatformIO Project Configuration
; ESP32-S3 + Wiznet W5500 TCP Client/Server
; W5500 wired to SPI2 (HSPI) on ESP32-S3

[env:esp32-s3]
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    khoih-prog/Ethernet_Generic @ ^2.8.1
    bodmer/TFT_eSPI

build_flags =
    -Wl,-Map,.pio/build/esp32-s3/firmware.map
    -D CLIENT=1
    -DCORE_DEBUG_LEVEL=3
    ; ── W5500 chip select & reset ──────────────────────────────────────────────
    ; -DETHERNET_USE_ESP32=true
    ; Tell Ethernet_Generic which W5x00 chip is installed
    -D USING_W5500=true
    -D DISABLE_ALL_LIBRARY_WARNINGS=0

    ; -D ARDUINO_USB_MODE=1
    ; -D ARDUINO_USB_CDC_ON_BOOT=1

    -DDISABLE_ALL_LIBRARY_WARNINGS=0

    -DUSER_SETUP_LOADED=1
    -include ${PROJECT_SRC_DIR}/TFT.h

    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160

    -D USE_HSPI_PORT=0

;debug_server =
;    ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
;    -s ${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts
;    -f board/esp32s3-builtin.cfg
;    -c "adapter_khz 1000"
;-c "adapter serial 44:1B:F6:ED:F9:70"

;debug_tool       = esp-builtin
;upload_protocol  = esp-builtin
;build_type       = debug
;debug_init_break = tbreak setup

; Increase upload speed and enable USB CDC for serial monitor
upload_speed   = 921600
monitor_speed  = 115200
monitor_filters = esp32_exception_decoder

monitor_port = /dev/cu.wchusbserial312160
upload_port  = /dev/cu.wchusbserial312160

;monitor_port = /dev/tty.usbmodem3122301
;upload_port = /dev/tty.usbmodem3122301

; monitor_port = COM16
; upload_port = COM14

[env:esp32-s3-s]
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    khoih-prog/Ethernet_Generic @ ^2.8.1
    bodmer/TFT_eSPI

build_flags =
    -Wl,-Map,.pio/build/esp32-s3-s/firmware.map
    -Wl,--undefined=uxTopUsedPriority
    -D SERVER=1
    -DCORE_DEBUG_LEVEL=3
    ; ── W5500 chip select & reset ──────────────────────────────────────────────
    ; -DETHERNET_USE_ESP32=true
    ; Tell Ethernet_Generic which W5x00 chip is installed
    -D USING_W5500=true
    -D DISABLE_ALL_LIBRARY_WARNINGS=0

    ; -D ARDUINO_USB_MODE=0
    ; -D ARDUINO_USB_CDC_ON_BOOT=1

    -DDISABLE_ALL_LIBRARY_WARNINGS=0

    -DUSER_SETUP_LOADED=1
    -include ${PROJECT_SRC_DIR}/TFT.h

    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160

    -D USE_HSPI_PORT=0
    
; debug_server =
;     ${platformio.packages_dir}/tool-openocd-esp32/bin/openocd
;     -s ${platformio.packages_dir}/tool-openocd-esp32/share/openocd/scripts
;     -f board/esp32s3-builtin.cfg
;     -c "adapter_khz 1000"
; ;-c "adapter serial 44:1B:F6:ED:F9:70"

;debug_tool       = esp-builtin
;upload_protocol  = esp-builtin
;build_type       = debug
;debug_init_break = tbreak setup

; Increase upload speed and enable USB CDC for serial monitor
upload_speed   = 921600
monitor_speed  = 115200
monitor_filters = esp32_exception_decoder

monitor_port = /dev/tty.wchusbserial312150
upload_port  = /dev/tty.wchusbserial312150

; monitor_port = /dev/tty.wchusbserial312160
; upload_port  = /dev/tty.wchusbserial312160

; monitor_port = COM16
; upload_port = COM14


